document.write("Base: 2" + "<br>");
      document.write("Expoente: 8" + "<br><br>");
      document.write("2<sup>0</sup> = 1" + "<br>");
      document.write("2<sup>1</sup> = " + (2*1) + "<br>");
      document.write("2<sup>2</sup> = " + (2*2) + "<br>");
      document.write("2<sup>3</sup> = " + (2*2*2) + "<br>");
      document.write("2<sup>4</sup> = " + (2*2*2*2) + "<br>");
      document.write("2<sup>5</sup> = " + (2*2*2*2*2) + "<br>");
      document.write("2<sup>6</sup> = " + (2*2*2*2*2*2) + "<br>");
      document.write("2<sup>7</sup> = " + (2*2*2*2*2*2*2) + "<br>");
      document.write("2<sup>8</sup> = " + (2*2*2*2*2*2*2*2) + "<br>");